[tool.poetry]
name = "pycounts_go2026"
#name = "pycounts"
version = "0.3.0"
description = "Calculate word counts in a text file"
authors = ["Morty Chen"]
license = "MIT"
readme = "README.md"

packages = [
    {from = "src", include = "pycounts"}  # 保持 src/pycounts 不变
]

[tool.poetry.dependencies]
python = ">=3.12"
matplotlib = ">=3.4.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "myst-nb (>=1.4.0,<2.0.0) ; python_version >= \"3.9\" and python_version < \"4.0\"",
    "sphinx-autoapi (>=3.8.0,<4.0.0)",
    "sphinx-rtd-theme (>=3.1.0,<4.0.0)",
    "python-semantic-release (>=10.6.1,<11.0.0) ; python_version >= \"3.8\" and python_version < \"4.0\""
]

[tool.semantic_release]
#version_variable = "pyproject.toml:project.version"
version_variable = "pyproject.toml:tool.poetry.version"
allow_zero_version = true
major_on_zero = false

